version: "3.8"

services:

  magnetar:
    build: .
    image: magnetar
    container_name: magnetar
    hostname: ${MAGNETAR_HOSTNAME}
    restart: on-failure
    expose:
      - ${MAGNETAR_PORT}
    ports:
      - ${MAGNETAR_PORT}:${MAGNETAR_PORT}
    environment:
      - NATS_ADDRESS=${NATS_HOSTNAME}:${NATS_PORT}
      - ETCD_ADDRESS=${ETCD_HOSTNAME}:${ETCD_PORT}
      - REGISTRATION_SUBJECT=${REGISTRATION_SUBJECT}
      - MAGNETAR_ADDRESS=:${MAGNETAR_PORT}
    networks:
      - network
    depends_on:
      - nats
      - etcd

  star:
    build:
      context: ..
      dockerfile: star/Dockerfile
    image: star
    container_name: star
    hostname: ${STAR_HOSTNAME}
    environment:
      - NATS_ADDRESS=${NATS_HOSTNAME}:${NATS_PORT}
      - REGISTRATION_SUBJECT=${REGISTRATION_SUBJECT}
      - REGISTRATION_REQ_TIMEOUT_MILLISECONDS=${REGISTRATION_REQ_TIMEOUT_MILLISECONDS}
      - MAX_REGISTRATION_RETRIES=${MAX_REGISTRATION_RETRIES}
      - NODE_ID_DIR_PATH=${NODE_ID_DIR_PATH}
      - NODE_ID_FILE_NAME=${NODE_ID_FILE_NAME}
    networks:
      - network
    volumes:
      - type: bind
        source: ..
        target: ${NODE_ID_DIR_PATH}
    depends_on:
      - nats
      - magnetar

  nats:
    image: nats:latest
    container_name: nats
    hostname: ${NATS_HOSTNAME}
    restart: on-failure
    networks:
      - network

  etcd:
    image: 'bitnami/etcd:latest'
    container_name: etcd
    hostname: ${ETCD_HOSTNAME}
    expose:
      - ${ETCD_PORT}
    ports:
      - ${ETCD_PORT}:${ETCD_PORT}
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://${ETCD_HOSTNAME}:${ETCD_PORT}
    networks:
      - network

networks:
  network:
    driver: bridge